# Generated by Django 5.1.4 on 2025-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_user_telegram_id_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.TextField(blank=True, null=True, verbose_name='Телефон получателя'),
        ),
    ]
